apiVersion: v1
entries:
  ollama:
  - annotations:
      artifacthub.io/category: ai-machine-learning
      artifacthub.io/changes: |
        - kind: changed
          description: upgrade app version to 0.3.14
    apiVersion: v2
    appVersion: 0.3.14
    created: "2024-10-27T02:43:14.272276+02:00"
    description: Get up and running with large language models locally.
    digest: 6f345baa25fd444ed099565cd388d980ff11c36a32b6ac30d6b8fcfaa455a634
    home: https://ollama.ai/
    icon: https://ollama.ai/public/ollama.png
    keywords:
    - ai
    - llm
    - llama
    - mistral
    kubeVersion: ^1.16.0-0
    maintainers:
    - email: contact@otwld.com
      name: OTWLD
    name: ollama
    sources:
    - https://github.com/ollama/ollama
    - https://github.com/otwld/ollama-helm
    type: application
    urls:
    - https://mbtraore.github.io/olop-helm-charts/ollama-0.63.0.tgz
    version: 0.63.0
  open-webui:
  - annotations:
      licenses: MIT
    apiVersion: v2
    appVersion: 0.1.107
    created: "2024-10-27T02:43:14.28115+02:00"
    dependencies:
    - condition: ollama.enabled
      name: ollama
      repository: https://otwld.github.io/ollama-helm/
      version: 0.63.0
    description: "Chart to deploy Open WebUI, a ChatGPT-Style Web UI Client for Ollama
      \U0001F999."
    digest: eb46a4b5db272bbc9d1bd1882f16936aa77a35ddb383b7777d11729692278ea8
    home: https://openwebui.com/
    icon: https://openwebui.com/favicon.png/
    keywords:
    - ai
    - ollama
    - llm
    - llama
    maintainers:
    - email: mb.traore@outlook.com
      name: mbtraore
      url: https://mbarre.fr
    name: open-webui
    sources:
    - https://github.com/jmorganca/ollama/
    - https://github.com/open-webui/open-webui
    - https://github.com/braveokafor/open-webui-helm/
    urls:
    - https://mbtraore.github.io/olop-helm-charts/open-webui-3.4.0.tgz
    version: 3.4.0
generated: "2024-10-27T02:43:14.2704+02:00"
